<?php

namespace App\Models;

use EloquentFilter\Filterable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * @property mixed|string $unique_code
 */
class Payment extends Model
{
    use HasFactory,Filterable;

    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function(Payment $payment) {
        $payment->unique_code = uniqid();
        });
    }

    public function sale(): BelongsTo
    {
        return $this->belongsTo(Sale::class);
    }

    public function Gateway(): HasMany
    {
        return $this->hasMany(Gateway::class);
    }

    public function customer()
    {
        return $this->hasOneThrough(Customer::class, Sale::class);
    }
}
